- name: Create User admin1 and admin2
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Run a script to Create User
      ansible.builtin.script: ../assets/Create_Admin_user.sh
      environment:
        BUCKET_NAME: "{{ lookup('env', 'BUCKET_NAME') }}"
