- name: Update and upgrade packages on all Linux servers
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Pritunl On Ubuntu
      ansible.builtin.script: ../assets/Ubuntu_Pritunl.sh
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Pritunl On Amazon
      ansible.builtin.script: ../assets/Amazon_Pritunl.sh
      when: ansible_facts['os_family'] in ["RedHat", "Amazon"]
